# Generated by Django 2.1.4 on 2019-01-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0003_auto_20190104_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dinner_Platters',
            new_name='Dinner_Platter',
        ),
        migrations.RenameModel(
            old_name='Salads',
            new_name='Salad',
        ),
        migrations.AddField(
            model_name='shopping_cart_item',
            name='large_price',
            field=models.FloatField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart_item',
            name='small_price',
            field=models.FloatField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart_item',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub',
            name='built_in_topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinochios.Topping'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='Subs', to='pinochios.Topping'),
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
