# Generated by Django 2.1.4 on 2019-01-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0005_auto_20190105_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart_item',
            name='type',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
