# Generated by Django 2.1.4 on 2019-01-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0006_shopping_cart_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart_item',
            old_name='type',
            new_name='type_of',
        ),
    ]
