# Generated by Django 2.1.4 on 2019-01-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0012_auto_20190105_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='large_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='small_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
